# syntax=docker/dockerfile:1

FROM node:20-alpine

WORKDIR /app

# Copy package.json & install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Environment
ENV NODE_ENV=development
ENV NEXT_PUBLIC_API_URL=http://backend:8000

# Run in dev mode
CMD ["npm", "run", "dev"]
